In [1]:
# from preprocessors.bloomberg import download_data_bbg

In [2]:
import pdblp
import pandas as pd
from datetime import datetime
from preprocessors.bbg import bbg_download_data_asset, bbg_download_data_eco_indicators, bbg_data_intraday, bbg_data_intraday_simple
import blpapi
from preprocessors.preprocessors import DataProcessor
from configs import tickers

In [14]:
start_date = "2020-01-01"
end_date = "2020-06-10"
interval = 60

tickers = ["AAPL US EQUITY", "NVDA US Equity"]

try:
    # con = pdblp.BCon(debug=False, port=8194, timeout=5000)
    # con.start()
    intraday = bbg_data_intraday(tickers, start_date, end_date, interval=60)
    # con.stop()
except Exception as e:
    print(f"Could not start Bloomberg API connection. error: {e}")
    raise
# try:
#     # con = pdblp.BCon(debug=False, port=8194, timeout=5000)
#     # con.start()
#     intraday = bbg_data_intraday_simple(tickers)
#     # con.stop()
# except Exception as e:
#     print(f"Could not start Bloomberg API connection. error: {e}")
#     raise

Error fetching data for ticker AAPL US EQUITY on 2020-01-01T09:30:00 to 2020-01-02T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-02T09:30:00 to 2020-01-03T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-03T09:30:00 to 2020-01-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-06T09:30:00 to 2020-01-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-07T09:30:00 to 2020-01-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-08T09:30:00 to 2020-01-09T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-09T09:30:00 to 2020-01-10T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-10T09:30:00 to 2020-01-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-13T09:30:00 to 2020-01-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-14T09:30:00 to 2020-01-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-15T09:30:00 to 2020-01-16T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-16T09:30:00 to 2020-01-17T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-17T09:30:00 to 2020-01-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-20T09:30:00 to 2020-01-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-21T09:30:00 to 2020-01-22T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-22T09:30:00 to 2020-01-23T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-23T09:30:00 to 2020-01-24T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-24T09:30:00 to 2020-01-25T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-27T09:30:00 to 2020-01-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-28T09:30:00 to 2020-01-29T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-29T09:30:00 to 2020-01-30T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-30T09:30:00 to 2020-01-31T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-01-31T09:30:00 to 2020-02-01T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-03T09:30:00 to 2020-02-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-04T09:30:00 to 2020-02-05T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-05T09:30:00 to 2020-02-06T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-06T09:30:00 to 2020-02-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-07T09:30:00 to 2020-02-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-10T09:30:00 to 2020-02-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-11T09:30:00 to 2020-02-12T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-12T09:30:00 to 2020-02-13T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-13T09:30:00 to 2020-02-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-14T09:30:00 to 2020-02-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-17T09:30:00 to 2020-02-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-18T09:30:00 to 2020-02-19T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-19T09:30:00 to 2020-02-20T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-20T09:30:00 to 2020-02-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-21T09:30:00 to 2020-02-22T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-24T09:30:00 to 2020-02-25T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-25T09:30:00 to 2020-02-26T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-26T09:30:00 to 2020-02-27T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-27T09:30:00 to 2020-02-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-02-28T09:30:00 to 2020-02-29T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-02T09:30:00 to 2020-03-03T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-03T09:30:00 to 2020-03-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-04T09:30:00 to 2020-03-05T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-05T09:30:00 to 2020-03-06T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-06T09:30:00 to 2020-03-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-09T09:30:00 to 2020-03-10T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-10T09:30:00 to 2020-03-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-11T09:30:00 to 2020-03-12T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-12T09:30:00 to 2020-03-13T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-13T09:30:00 to 2020-03-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-16T09:30:00 to 2020-03-17T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-17T09:30:00 to 2020-03-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-18T09:30:00 to 2020-03-19T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-19T09:30:00 to 2020-03-20T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-20T09:30:00 to 2020-03-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-23T09:30:00 to 2020-03-24T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-24T09:30:00 to 2020-03-25T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-25T09:30:00 to 2020-03-26T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-26T09:30:00 to 2020-03-27T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-27T09:30:00 to 2020-03-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-30T09:30:00 to 2020-03-31T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-03-31T09:30:00 to 2020-04-01T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-01T09:30:00 to 2020-04-02T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-02T09:30:00 to 2020-04-03T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-03T09:30:00 to 2020-04-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-06T09:30:00 to 2020-04-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-07T09:30:00 to 2020-04-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-08T09:30:00 to 2020-04-09T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-09T09:30:00 to 2020-04-10T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-10T09:30:00 to 2020-04-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-13T09:30:00 to 2020-04-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-14T09:30:00 to 2020-04-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-15T09:30:00 to 2020-04-16T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-16T09:30:00 to 2020-04-17T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-17T09:30:00 to 2020-04-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-20T09:30:00 to 2020-04-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-21T09:30:00 to 2020-04-22T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-22T09:30:00 to 2020-04-23T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-23T09:30:00 to 2020-04-24T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-24T09:30:00 to 2020-04-25T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-27T09:30:00 to 2020-04-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-28T09:30:00 to 2020-04-29T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-29T09:30:00 to 2020-04-30T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-04-30T09:30:00 to 2020-05-01T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-01T09:30:00 to 2020-05-02T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-04T09:30:00 to 2020-05-05T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-05T09:30:00 to 2020-05-06T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-06T09:30:00 to 2020-05-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-07T09:30:00 to 2020-05-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-08T09:30:00 to 2020-05-09T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-11T09:30:00 to 2020-05-12T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-12T09:30:00 to 2020-05-13T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-13T09:30:00 to 2020-05-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-14T09:30:00 to 2020-05-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-15T09:30:00 to 2020-05-16T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-18T09:30:00 to 2020-05-19T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-19T09:30:00 to 2020-05-20T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-20T09:30:00 to 2020-05-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-21T09:30:00 to 2020-05-22T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-22T09:30:00 to 2020-05-23T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-25T09:30:00 to 2020-05-26T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-26T09:30:00 to 2020-05-27T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-27T09:30:00 to 2020-05-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-28T09:30:00 to 2020-05-29T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-05-29T09:30:00 to 2020-05-30T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-01T09:30:00 to 2020-06-02T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-02T09:30:00 to 2020-06-03T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-03T09:30:00 to 2020-06-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-04T09:30:00 to 2020-06-05T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-05T09:30:00 to 2020-06-06T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-08T09:30:00 to 2020-06-09T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-09T09:30:00 to 2020-06-10T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker AAPL US EQUITY on 2020-06-10T09:30:00 to 2020-06-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-01T09:30:00 to 2020-01-02T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-02T09:30:00 to 2020-01-03T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-03T09:30:00 to 2020-01-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-06T09:30:00 to 2020-01-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-07T09:30:00 to 2020-01-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-08T09:30:00 to 2020-01-09T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-09T09:30:00 to 2020-01-10T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-10T09:30:00 to 2020-01-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-13T09:30:00 to 2020-01-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-14T09:30:00 to 2020-01-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-15T09:30:00 to 2020-01-16T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-16T09:30:00 to 2020-01-17T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-17T09:30:00 to 2020-01-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-20T09:30:00 to 2020-01-21T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-21T09:30:00 to 2020-01-22T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-22T09:30:00 to 2020-01-23T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-23T09:30:00 to 2020-01-24T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-24T09:30:00 to 2020-01-25T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-27T09:30:00 to 2020-01-28T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-28T09:30:00 to 2020-01-29T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-29T09:30:00 to 2020-01-30T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-30T09:30:00 to 2020-01-31T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-01-31T09:30:00 to 2020-02-01T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-03T09:30:00 to 2020-02-04T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-04T09:30:00 to 2020-02-05T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-05T09:30:00 to 2020-02-06T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-06T09:30:00 to 2020-02-07T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-07T09:30:00 to 2020-02-08T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-10T09:30:00 to 2020-02-11T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-11T09:30:00 to 2020-02-12T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-12T09:30:00 to 2020-02-13T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-13T09:30:00 to 2020-02-14T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-14T09:30:00 to 2020-02-15T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-17T09:30:00 to 2020-02-18T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-18T09:30:00 to 2020-02-19T15:30:00: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity on 2020-02-19T09:30:00 to 2020-02-20T15:30:00: "None of ['time'] are in the columns"

In [15]:
intraday

Empty DataFrame
Columns: []
Index: []

In [13]:
con = pdblp.BCon(debug=False, port=8194, timeout=5000)
start = '2023-06-19T09:30:00'
con.start()
df3 = con.bdib('SPY Equity', start, '2023-07-19T15:30:00', 'TRADE', interval=60)
con.stop()

In [12]:
df3

                        open     high      low   close    volume  numEvents
time
2023-06-20 13:30:00  437.450  438.170  435.063  435.19  12923767      73935
2023-06-20 14:30:00  435.190  436.370  435.030  435.92   7804381      48022
2023-06-20 15:30:00  435.910  437.360  435.850  437.23   5574544      35506
2023-06-20 16:30:00  437.240  438.370  437.060  438.08   7469589      45494
2023-06-20 17:30:00  438.075  438.235  437.300  438.01   4584109      27924
...                      ...      ...      ...     ...       ...        ...
2023-07-18 17:30:00  453.200  454.320  453.130  454.31   5513103      31542
2023-07-18 18:30:00  454.315  454.845  453.760  454.44   6661859      38523
2023-07-18 19:30:00  454.440  454.860  454.090  454.19  16094695      69972
2023-07-19 13:30:00  455.010  456.340  455.010  455.83  10503693      64254
2023-07-19 14:30:00  455.830  456.170  454.600  455.79   7948530      49082

[142 rows x 6 columns]

In [3]:

print(tickers.ECONOMIC_INDICATOR_TICKERS)

['.AAIIB2B G Index', '.DMASPX G Index', '.NETBULL G Index', '.NGCM% G Index', '.SPE10YBR G Index', '.SPPE2YBR G Index', '.SPX%FWD G Index', '.SPXPE G Index', 'AAIIBEAR Index', 'AAIIBOND Index', 'AAIIBULL Index', 'AAIICASH Index', 'AAIINEUT Index', 'AAIISTCK Index', 'AAIISVND Index', 'ADVN Index', 'ARMS Index', 'AUD Curncy', 'BCOMPR Index', 'BIFIFEDA Index', 'BIFIFEDM Index', 'BSPGCPUS Index', 'CLL Index', 'CONSP5MD Index', 'CONSSENT Index', 'CONSSENY Index', 'CPI CHNG Index', 'CVIX Index', 'DBQSGSI Index', 'DOEASCRD Index', 'DXY Curncy', 'ECSURPUS Index', 'ECSUSUUS Index', 'EHNFUS Index', 'EHUPUS Index', 'EURUSDV1M Curncy', 'EURUSDV1Y Curncy', 'FARBAST Index', 'FEDL01 Index', 'GDP CUR$ Index', 'GSCBHRSB Index', 'GSERCAUS Index', 'GSUSCAI Index', 'GT10 Govt', 'GT2 Govt', 'GT30 Govt', 'GT5 Govt', 'IMM0ECON Index', 'IMMTENCN Index', 'INDU Index', 'INJCJC Index', 'INJCSP Index', 'JPMEQGSI Index', 'JPMEQGSI Index', 'LAGITOTL Index', 'LEI 6MAN Index', 'LEI CHNG Index', 'LEI TOTL Index', 'LEI YOY Index', 'MOVE Index', 'MSXAMSIL Index', 'MSXAMSIS Index', 'NAPMNIS Index', 'NAPMNISH Index', 'NAPMNISL Index', 'NAPMNISS Index', 'NAPMNMI Index', 'NAPMPMI Index', 'NAPMPMI Index', 'NDX Index', 'NFCINBAA Index', 'NFCINHY Index', 'NFP T Index', 'NFP TCH Index', 'NFP TCH Index', 'NFP TMOM Index', 'NQBUY Index', 'NTMBHA Index', 'NTMBHV Index', 'NWHLAMHI Index', 'NWHLAMHL Index', 'NWHLNYHI Index', 'NWHLNYHL Index', 'NWHLNYLO Index', 'NWHLSEAM Index', 'NWHLSEND Index', 'NWHLSENY Index', 'NYAAD Index', 'NYSEVALU Index', 'NYSEVOL Index', 'OPCVTPCR Index', 'PCE DEFM Index', 'PCRTEQTY Index', 'PCRTTOTL Index', 'PCUSEQTR Index', 'PCUSINXR Index', 'PITLCHNG Index', 'PPI CHNG Index', 'PPI YOY Index', 'RVX Index', 'SFFRNEWS Index', 'SGXQIN01 Index', 'SKEW Index', 'SPGSCI Index', 'SUM OSC Index', 'TRADCAND Index', 'TRADCNYC Index', 'TRADHIGH Index', 'TRADHILO Index', 'TRADPAUS Index', 'TRAN Index', 'UMBTSENT Index', 'USDJPYV1M Curncy', 'USDJPYV3M Curncy', 'USEPSPVX Index', 'USPESPGX Index', 'USPESPPE Index', 'USURTOT Index', 'USYC1030 Index', 'USYC2Y10 Index', 'USYC2Y5Y Index', 'USYC3M2Y Index', 'USYC5Y30 Index', 'VIX Index', 'VIX3M Index', 'CESIUSD Index']

In [4]:
eco_tic1 = pd.read_csv("G:\My Drive\eco_index_fetch_31July.csv")
eco_tic1["Index"].tolist()

['.AAIIB2B G Index',
 '.DMASPX G Index',
 '.NETBULL G Index',
 '.NGCM% G Index',
 '.SPE10YBR G Index',
 '.SPPE2YBR G Index',
 '.SPX%FWD G Index',
 '.SPXPE G Index',
 'AAIIBEAR Index',
 'AAIIBOND Index',
 'AAIIBULL Index',
 'AAIICASH Index',
 'AAIINEUT Index',
 'AAIISTCK Index',
 'AAIISVND Index',
 'ADVN Index',
 'ARMS Index',
 'AUD Curncy',
 'BCOMPR Index',
 'BIFIFEDA Index',
 'BIFIFEDM Index',
 'BSPGCPUS Index',
 'CLL Index',
 'CONSP5MD Index',
 'CONSSENT Index',
 'CONSSENY Index',
 'CPI CHNG Index',
 'CVIX Index',
 'DBQSGSI Index',
 'DOEASCRD Index',
 'DXY Curncy',
 'ECSURPUS Index',
 'ECSUSUUS Index',
 'EHNFUS Index',
 'EHUPUS Index',
 'EURUSDV1M Curncy',
 'EURUSDV1Y Curncy',
 'FARBAST Index',
 'FEDL01 Index',
 'GDP CUR$ Index',
 'GSCBHRSB Index',
 'GSERCAUS Index',
 'GSUSCAI Index',
 'GT10 Govt',
 'GT2 Govt',
 'GT30 Govt',
 'GT5 Govt',
 'IMM0ECON Index',
 'IMMTENCN Index',
 'INDU Index',
 'INJCJC Index',
 'INJCSP Index',
 'JPMEQGSI Index',
 'JPMEQGSI Index',
 'LAGITOTL Index',
 'LEI 6MAN Index',
 'LEI CHNG Index',
 'LEI TOTL Index',
 'LEI YOY Index',
 'MOVE Index',
 'MSXAMSIL Index',
 'MSXAMSIS Index',
 'NAPMNIS Index',
 'NAPMNISH Index',
 'NAPMNISL Index',
 'NAPMNISS Index',
 'NAPMNMI Index',
 'NAPMPMI Index',
 'NAPMPMI Index',
 'NDX Index',
 'NFCINBAA Index',
 'NFCINHY Index',
 'NFP T Index',
 'NFP TCH Index',
 'NFP TCH Index',
 'NFP TMOM Index',
 'NQBUY Index',
 'NTMBHA Index',
 'NTMBHV Index',
 'NWHLAMHI Index',
 'NWHLAMHL Index',
 'NWHLNYHI Index',
 'NWHLNYHL Index',
 'NWHLNYLO Index',
 'NWHLSEAM Index',
 'NWHLSEND Index',
 'NWHLSENY Index',
 'NYAAD Index',
 'NYSEVALU Index',
 'NYSEVOL Index',
 'OPCVTPCR Index',
 'PCE DEFM Index',
 'PCRTEQTY Index',
 'PCRTTOTL Index',
 'PCUSEQTR Index',
 'PCUSINXR Index',
 'PITLCHNG Index',
 'PPI CHNG Index',
 'PPI YOY Index',
 'RVX Index',
 'SFFRNEWS Index',
 'SGXQIN01 Index',
 'SKEW Index',
 'SPGSCI Index',
 'SUM OSC Index',
 'TRADCAND Index',
 'TRADCNYC Index',
 'TRADHIGH Index',
 'TRADHILO Index',
 'TRADPAUS Index',
 'TRAN Index',
 'UMBTSENT Index',
 'USDJPYV1M Curncy',
 'USDJPYV3M Curncy',
 'USEPSPVX Index',
 'USPESPGX Index',
 'USPESPPE Index',
 'USURTOT Index',
 'USYC1030 Index',
 'USYC2Y10 Index',
 'USYC2Y5Y Index',
 'USYC3M2Y Index',
 'USYC5Y30 Index',
 'VIX Index',
 'VIX3M Index',
 'CESIUSD Index']

Intraday Data BBG

In [5]:
tickers = pd.read_csv("vol_stocks.csv")
tickers = tickers['growth_tic'].tolist()
tickers

trial_run = ['AAPL US Equity',
]

In [6]:
start_date="2015-01-01"
end_date="2023-07-25"

try:
    con = pdblp.BCon(debug=False, port=8194, timeout=5000)
    con.start()
    # eco_df = bbg_download_data_eco_indicators(tickers_eco, fields, start_date, end_date, con)
    intraday = bbg_data_intraday(trial_run, start_date, end_date, interval=60, con=con)
    con.stop()
except Exception as e:
    print(f"Could not start Bloomberg API connection. error: {e}")
    raise

Error fetching data for ticker AAPL US Equity: Cannot convert to ENUM type. (0x0004000c)

In [8]:
intraday

Empty DataFrame
Columns: [index]
Index: []

In [2]:
tickers = ['AAPL US Equity']
start_date = "2023-01-01"
end_date = "2023-08-01"
interval = 60  # for 1-hour bars

data = bbg_data_intraday_xbbg(tickers, start_date, end_date, interval)

In [3]:
data

      index      0
0  (type, )  asset

In [12]:
con = pdblp.BCon(debug=False, port=8194, timeout=5000)
con.start()
df3 = con.bdib('SPY Equity', '2023-06-19T09:30:00', '2023-07-19T15:30:00', 'TRADE', interval=60)
df3.head()
con.stop()

In [13]:
df3

                        open     high      low   close    volume  numEvents
time
2023-06-20 13:30:00  437.450  438.170  435.063  435.19  12923767      73935
2023-06-20 14:30:00  435.190  436.370  435.030  435.92   7804381      48022
2023-06-20 15:30:00  435.910  437.360  435.850  437.23   5574544      35506
2023-06-20 16:30:00  437.240  438.370  437.060  438.08   7469589      45494
2023-06-20 17:30:00  438.075  438.235  437.300  438.01   4584109      27924
...                      ...      ...      ...     ...       ...        ...
2023-07-18 17:30:00  453.200  454.320  453.130  454.31   5513103      31542
2023-07-18 18:30:00  454.315  454.845  453.760  454.44   6661859      38523
2023-07-18 19:30:00  454.440  454.860  454.090  454.19  16094695      69972
2023-07-19 13:30:00  455.010  456.340  455.010  455.83  10503693      64254
2023-07-19 14:30:00  455.830  456.170  454.600  455.79   7948530      49082

[142 rows x 6 columns]

In [2]:
start_date = "2023-01-01"
end_date = "2023-01-10"
interval = 60

tickers = ["AAPL US Equity", "IBM US Equity", "NVDA US Equity"]

try:
    con = pdblp.BCon(debug=False, port=8194, timeout=5000)
    con.start()
    intraday = bbg_data_intraday(tickers, start_date, end_date, interval, con)
    con.stop()
except Exception as e:
    print(f"Could not start Bloomberg API connection. error: {e}")
    raise

2023-01-01T09:30:00
2023-01-10T15:30:00
Error fetching data for ticker AAPL US Equity: "None of ['time'] are in the columns"
Error fetching data for ticker IBM US Equity: "None of ['time'] are in the columns"
Error fetching data for ticker NVDA US Equity: "None of ['time'] are in the columns"

In [12]:

tickers_asset = ['SPX Index']
tickers_eco = ['CPI YOY Index','NFP NYCH Index', "EUR Curncy"]
# tickers_eco = tickers.ECONOMIC_INDICATOR_TICKERS

fields = ['LAST_PRICE',"PX_LOW","PX_HIGH","PX_Open","PX_VOLUME"]
start_date = '1980-01-01'
end_date = '2023-07-28'

try:
    con = pdblp.BCon(debug=False, port=8194, timeout=5000)
    con.start()
    # eco_df = bbg_download_data_eco_indicators(tickers_eco, fields, start_date, end_date, con)
    asset_df = bbg_download_data_asset(tickers_asset, fields, start_date, end_date, con)
    con.stop()
except Exception as e:
    print(f"Could not start Bloomberg API connection. error: {e}")
    raise

In [13]:
asset_df

,date,tic,LAST_PRICE,PX_HIGH,PX_LOW,PX_Open,PX_VOLUME,type
0,1980-01-02,SPX Index,105.76,105.76,105.76,105.76,NaN,asset
1,1980-01-03,SPX Index,105.22,105.22,105.22,105.22,NaN,asset
2,1980-01-04,SPX Index,106.52,106.52,106.52,106.52,NaN,asset
3,1980-01-07,SPX Index,106.81,106.81,106.81,106.81,NaN,asset
4,1980-01-08,SPX Index,108.95,108.95,108.95,108.95,NaN,asset
...,...,...,...,...,...,...,...,...
10998,2023-07-24,SPX Index,4554.64,4563.41,4541.29,4543.39,550797536.0,asset
10999,2023-07-25,SPX Index,4567.46,4580.62,4552.42,4555.19,597126166.0,asset
11000,2023-07-26,SPX Index,4566.75,4582.47,4547.58,4558.96,614526566.0,asset
11001,2023-07-27,SPX Index,4537.41,4607.07,4528.56,4598.26,713687682.0,asset
11002,2023-07-28,SPX Index,4582.23,4590.16,4564.01,4565.75,647234729.0,asset

In [7]:
# eco_df.to_pickle('eco_df_large_since_1980.pkl')
asset_df.to_pickle('spx_df_since_1980_OHVL.pkl')

In [21]:
# eco_df.to_csv('eco_df_large_since_1980.csv')
# asset_df.to_csv('spx_df_since_1980.csv')

In [11]:
# dp = DataProcessor()
# filled_df = dp.fill_eco_data(eco_df)
def fill_eco_data(df: pd.DataFrame) -> pd.DataFrame:
    #Forward Fill
    df = df.fillna(method="ffill")
    #Backward fill with mean value
    for col in df.columns:
        if df[col].isna().any():
            mean_value = df[col].mean()
            df[col] = df[col].fillna(value=mean_value)
  
    return df


filled_df = fill_eco_data(eco_df)
filled_df

         date  CPI YOY Index  NFP NYCH Index  EUR Curncy
0  2023-01-02       6.363636     4858.818182      1.0667
1  2023-01-03       6.363636     4858.818182      1.0548
2  2023-01-04       6.363636     4858.818182      1.0604
3  2023-01-05       6.363636     4858.818182      1.0522
4  2023-01-06       6.363636     4858.818182      1.0644
5  2023-01-09       6.363636     4858.818182      1.0730
6  2023-01-10       6.363636     4858.818182      1.0733
7  2023-01-11       6.363636     4858.818182      1.0757
8  2023-01-12       6.363636     4858.818182      1.0853
9  2023-01-13       6.363636     4858.818182      1.0830
10 2023-01-16       6.363636     4858.818182      1.0822
11 2023-01-17       6.363636     4858.818182      1.0788
12 2023-01-18       6.363636     4858.818182      1.0794
13 2023-01-19       6.363636     4858.818182      1.0833
14 2023-01-20       6.363636     4858.818182      1.0856
15 2023-01-23       6.363636     4858.818182      1.0872
16 2023-01-24       6.363636     4858.818182      1.0887
17 2023-01-25       6.363636     4858.818182      1.0916
18 2023-01-26       6.363636     4858.818182      1.0892
19 2023-01-27       6.363636     4858.818182      1.0868
20 2023-01-30       6.363636     4858.818182      1.0851
21 2023-01-31       6.400000     4907.000000      1.0863
22 2023-02-01       6.400000     4907.000000      1.0990
23 2023-02-02       6.400000     4907.000000      1.0910
24 2023-02-03       6.400000     4907.000000      1.0795
25 2023-02-06       6.400000     4907.000000      1.0726
26 2023-02-07       6.400000     4907.000000      1.0726
27 2023-02-08       6.400000     4907.000000      1.0712
28 2023-02-09       6.400000     4907.000000      1.0740
29 2023-02-10       6.400000     4907.000000      1.0678
30 2023-02-13       6.400000     4907.000000      1.0723
31 2023-02-14       6.400000     4907.000000      1.0738
32 2023-02-15       6.400000     4907.000000      1.0689
33 2023-02-16       6.400000     4907.000000      1.0674
34 2023-02-17       6.400000     4907.000000      1.0695
35 2023-02-20       6.400000     4907.000000      1.0686
36 2023-02-21       6.400000     4907.000000      1.0648
37 2023-02-22       6.400000     4907.000000      1.0605
38 2023-02-23       6.400000     4907.000000      1.0596
39 2023-02-24       6.400000     4907.000000      1.0548
40 2023-02-27       6.400000     4907.000000      1.0609
41 2023-02-28       6.000000     4377.000000      1.0576
42 2023-03-01       6.000000     4377.000000      1.0668

In [6]:
asset_df.tail()

         date        tic  LAST_PRICE   type
75 2023-02-23  NDX Index    12180.14  asset
76 2023-02-24  NDX Index    11969.65  asset
77 2023-02-27  NDX Index    12057.79  asset
78 2023-02-28  NDX Index    12042.12  asset
79 2023-03-01  NDX Index    11938.57  asset

In [7]:
# df.index = df.date.factorize()[0]
# df.sort_values(by=['date', 'tic'], inplace=True)
# df

In [8]:
# df.to_csv('bbg_download2.csv')