In [1]:
# from preprocessors.bloomberg import download_data_bbg

In [1]:
import pdblp
import pandas as pd
from datetime import datetime
from preprocessors.bbg import bbg_download_data_asset, bbg_download_data_eco_indicators
import blpapi
from preprocessors.preprocessors import DataProcessor
from configs import tickers

ModuleNotFoundError: No module named 'pdblp'

In [17]:

print(tickers.ECONOMIC_INDICATOR_TICKERS)

['.AAIIB2B G Index', '.DMASPX G Index', '.NETBULL G Index', '.NGCM% G Index', '.SPE10YBR G Index', '.SPPE2YBR G Index', '.SPX%FWD G Index', '.SPXPE G Index', 'AAIIBEAR Index', 'AAIIBOND Index', 'AAIIBULL Index', 'AAIICASH Index', 'AAIINEUT Index', 'AAIISTCK Index', 'AAIISVND Index', 'ADVN Index', 'ARMS Index', 'AUD Curncy', 'BCOMPR Index', 'BIFIFEDA Index', 'BIFIFEDM Index', 'BSPGCPUS Index', 'CLL Index', 'CONSP5MD Index', 'CONSSENT Index', 'CONSSENY Index', 'CPI CHNG Index', 'CVIX Index', 'DBQSGSI Index', 'DOEASCRD Index', 'DXY Curncy', 'ECSURPUS Index', 'ECSUSUUS Index', 'EHNFUS Index', 'EHUPUS Index', 'EURUSDV1M Curncy', 'EURUSDV1Y Curncy', 'FARBAST Index', 'FEDL01 Index', 'GDP CUR$ Index', 'GSCBHRSB Index', 'GSERCAUS Index', 'GSUSCAI Index', 'GT10 Govt', 'GT2 Govt', 'GT30 Govt', 'GT5 Govt', 'IMM0ECON Index', 'IMMTENCN Index', 'INDU Index', 'INJCJC Index', 'INJCSP Index', 'JPMEQGSI Index', 'JPMEQGSI Index', 'LAGITOTL Index', 'LEI 6MAN Index', 'LEI CHNG Index', 'LEI TOTL Index', 'LEI YOY Index', 'MOVE Index', 'MSXAMSIL Index', 'MSXAMSIS Index', 'NAPMNIS Index', 'NAPMNISH Index', 'NAPMNISL Index', 'NAPMNISS Index', 'NAPMNMI Index', 'NAPMPMI Index', 'NAPMPMI Index', 'NDX Index', 'NFCINBAA Index', 'NFCINHY Index', 'NFP T Index', 'NFP TCH Index', 'NFP TCH Index', 'NFP TMOM Index', 'NQBUY Index', 'NTMBHA Index', 'NTMBHV Index', 'NWHLAMHI Index', 'NWHLAMHL Index', 'NWHLNYHI Index', 'NWHLNYHL Index', 'NWHLNYLO Index', 'NWHLSEAM Index', 'NWHLSEND Index', 'NWHLSENY Index', 'NYAAD Index', 'NYSEVALU Index', 'NYSEVOL Index', 'OPCVTPCR Index', 'PCE DEFM Index', 'PCRTEQTY Index', 'PCRTTOTL Index', 'PCUSEQTR Index', 'PCUSINXR Index', 'PITLCHNG Index', 'PPI CHNG Index', 'PPI YOY Index', 'RVX Index', 'SFFRNEWS Index', 'SGXQIN01 Index', 'SKEW Index', 'SPGSCI Index', 'SUM OSC Index', 'TRADCAND Index', 'TRADCNYC Index', 'TRADHIGH Index', 'TRADHILO Index', 'TRADPAUS Index', 'TRAN Index', 'UMBTSENT Index', 'USDJPYV1M Curncy', 'USDJPYV3M Curncy', 'USEPSPVX Index', 'USPESPGX Index', 'USPESPPE Index', 'USURTOT Index', 'USYC1030 Index', 'USYC2Y10 Index', 'USYC2Y5Y Index', 'USYC3M2Y Index', 'USYC5Y30 Index', 'VIX Index', 'VIX3M Index', 'CESIUSD Index']

In [14]:
eco_tic1 = pd.read_csv("G:\My Drive\eco_index_fetch_31July.csv")
eco_tic1["Index"].tolist()

['.AAIIB2B G Index',
 '.DMASPX G Index',
 '.NETBULL G Index',
 '.NGCM% G Index',
 '.SPE10YBR G Index',
 '.SPPE2YBR G Index',
 '.SPX%FWD G Index',
 '.SPXPE G Index',
 'AAIIBEAR Index',
 'AAIIBOND Index',
 'AAIIBULL Index',
 'AAIICASH Index',
 'AAIINEUT Index',
 'AAIISTCK Index',
 'AAIISVND Index',
 'ADVN Index',
 'ARMS Index',
 'AUD Curncy',
 'BCOMPR Index',
 'BIFIFEDA Index',
 'BIFIFEDM Index',
 'BSPGCPUS Index',
 'CLL Index',
 'CONSP5MD Index',
 'CONSSENT Index',
 'CONSSENY Index',
 'CPI CHNG Index',
 'CVIX Index',
 'DBQSGSI Index',
 'DOEASCRD Index',
 'DXY Curncy',
 'ECSURPUS Index',
 'ECSUSUUS Index',
 'EHNFUS Index',
 'EHUPUS Index',
 'EURUSDV1M Curncy',
 'EURUSDV1Y Curncy',
 'FARBAST Index',
 'FEDL01 Index',
 'GDP CUR$ Index',
 'GSCBHRSB Index',
 'GSERCAUS Index',
 'GSUSCAI Index',
 'GT10 Govt',
 'GT2 Govt',
 'GT30 Govt',
 'GT5 Govt',
 'IMM0ECON Index',
 'IMMTENCN Index',
 'INDU Index',
 'INJCJC Index',
 'INJCSP Index',
 'JPMEQGSI Index',
 'JPMEQGSI Index',
 'LAGITOTL Index',
 'LEI 6MAN Index',
 'LEI CHNG Index',
 'LEI TOTL Index',
 'LEI YOY Index',
 'MOVE Index',
 'MSXAMSIL Index',
 'MSXAMSIS Index',
 'NAPMNIS Index',
 'NAPMNISH Index',
 'NAPMNISL Index',
 'NAPMNISS Index',
 'NAPMNMI Index',
 'NAPMPMI Index',
 'NAPMPMI Index',
 'NDX Index',
 'NFCINBAA Index',
 'NFCINHY Index',
 'NFP T Index',
 'NFP TCH Index',
 'NFP TCH Index',
 'NFP TMOM Index',
 'NQBUY Index',
 'NTMBHA Index',
 'NTMBHV Index',
 'NWHLAMHI Index',
 'NWHLAMHL Index',
 'NWHLNYHI Index',
 'NWHLNYHL Index',
 'NWHLNYLO Index',
 'NWHLSEAM Index',
 'NWHLSEND Index',
 'NWHLSENY Index',
 'NYAAD Index',
 'NYSEVALU Index',
 'NYSEVOL Index',
 'OPCVTPCR Index',
 'PCE DEFM Index',
 'PCRTEQTY Index',
 'PCRTTOTL Index',
 'PCUSEQTR Index',
 'PCUSINXR Index',
 'PITLCHNG Index',
 'PPI CHNG Index',
 'PPI YOY Index',
 'RVX Index',
 'SFFRNEWS Index',
 'SGXQIN01 Index',
 'SKEW Index',
 'SPGSCI Index',
 'SUM OSC Index',
 'TRADCAND Index',
 'TRADCNYC Index',
 'TRADHIGH Index',
 'TRADHILO Index',
 'TRADPAUS Index',
 'TRAN Index',
 'UMBTSENT Index',
 'USDJPYV1M Curncy',
 'USDJPYV3M Curncy',
 'USEPSPVX Index',
 'USPESPGX Index',
 'USPESPPE Index',
 'USURTOT Index',
 'USYC1030 Index',
 'USYC2Y10 Index',
 'USYC2Y5Y Index',
 'USYC3M2Y Index',
 'USYC5Y30 Index',
 'VIX Index',
 'VIX3M Index',
 'CESIUSD Index']

In [18]:

tickers_asset = ['SPX Index']
tickers_eco = ['CPI YOY Index','NFP NYCH Index', "EUR Curncy"]
# tickers_eco = tickers.ECONOMIC_INDICATOR_TICKERS

fields = ['LAST_PRICE']
start_date = '1980-01-01'
end_date = '2023-07-28'

try:
    con = pdblp.BCon(debug=False, port=8194, timeout=5000)
    con.start()
    eco_df = bbg_download_data_eco_indicators(tickers_eco, fields, start_date, end_date, con)
    asset_df = bbg_download_data_asset(tickers_asset, fields, start_date, end_date, con)
    con.stop()
except Exception as e:
    print(f"Could not start Bloomberg API connection. error: {e}")
    raise

In [20]:
# eco_df.to_pickle('eco_df_large_since_1980.pkl')
# asset_df.to_pickle('spx_df_since_1980.pkl')

In [21]:
# eco_df.to_csv('eco_df_large_since_1980.csv')
# asset_df.to_csv('spx_df_since_1980.csv')

In [11]:
# dp = DataProcessor()
# filled_df = dp.fill_eco_data(eco_df)
def fill_eco_data(df: pd.DataFrame) -> pd.DataFrame:
    #Forward Fill
    df = df.fillna(method="ffill")
    #Backward fill with mean value
    for col in df.columns:
        if df[col].isna().any():
            mean_value = df[col].mean()
            df[col] = df[col].fillna(value=mean_value)
  
    return df


filled_df = fill_eco_data(eco_df)
filled_df

         date  CPI YOY Index  NFP NYCH Index  EUR Curncy
0  2023-01-02       6.363636     4858.818182      1.0667
1  2023-01-03       6.363636     4858.818182      1.0548
2  2023-01-04       6.363636     4858.818182      1.0604
3  2023-01-05       6.363636     4858.818182      1.0522
4  2023-01-06       6.363636     4858.818182      1.0644
5  2023-01-09       6.363636     4858.818182      1.0730
6  2023-01-10       6.363636     4858.818182      1.0733
7  2023-01-11       6.363636     4858.818182      1.0757
8  2023-01-12       6.363636     4858.818182      1.0853
9  2023-01-13       6.363636     4858.818182      1.0830
10 2023-01-16       6.363636     4858.818182      1.0822
11 2023-01-17       6.363636     4858.818182      1.0788
12 2023-01-18       6.363636     4858.818182      1.0794
13 2023-01-19       6.363636     4858.818182      1.0833
14 2023-01-20       6.363636     4858.818182      1.0856
15 2023-01-23       6.363636     4858.818182      1.0872
16 2023-01-24       6.363636     4858.818182      1.0887
17 2023-01-25       6.363636     4858.818182      1.0916
18 2023-01-26       6.363636     4858.818182      1.0892
19 2023-01-27       6.363636     4858.818182      1.0868
20 2023-01-30       6.363636     4858.818182      1.0851
21 2023-01-31       6.400000     4907.000000      1.0863
22 2023-02-01       6.400000     4907.000000      1.0990
23 2023-02-02       6.400000     4907.000000      1.0910
24 2023-02-03       6.400000     4907.000000      1.0795
25 2023-02-06       6.400000     4907.000000      1.0726
26 2023-02-07       6.400000     4907.000000      1.0726
27 2023-02-08       6.400000     4907.000000      1.0712
28 2023-02-09       6.400000     4907.000000      1.0740
29 2023-02-10       6.400000     4907.000000      1.0678
30 2023-02-13       6.400000     4907.000000      1.0723
31 2023-02-14       6.400000     4907.000000      1.0738
32 2023-02-15       6.400000     4907.000000      1.0689
33 2023-02-16       6.400000     4907.000000      1.0674
34 2023-02-17       6.400000     4907.000000      1.0695
35 2023-02-20       6.400000     4907.000000      1.0686
36 2023-02-21       6.400000     4907.000000      1.0648
37 2023-02-22       6.400000     4907.000000      1.0605
38 2023-02-23       6.400000     4907.000000      1.0596
39 2023-02-24       6.400000     4907.000000      1.0548
40 2023-02-27       6.400000     4907.000000      1.0609
41 2023-02-28       6.000000     4377.000000      1.0576
42 2023-03-01       6.000000     4377.000000      1.0668

In [6]:
asset_df.tail()

         date        tic  LAST_PRICE   type
75 2023-02-23  NDX Index    12180.14  asset
76 2023-02-24  NDX Index    11969.65  asset
77 2023-02-27  NDX Index    12057.79  asset
78 2023-02-28  NDX Index    12042.12  asset
79 2023-03-01  NDX Index    11938.57  asset

In [7]:
# df.index = df.date.factorize()[0]
# df.sort_values(by=['date', 'tic'], inplace=True)
# df

In [8]:
# df.to_csv('bbg_download2.csv')